Add Test
JulianSobott/OOP_TestExam pull request #8
Opened 2020-07-01 13:57 UTC by SimonRuttmann

2020-07-01 13:58 UTC, SimonRuttmann commented on submissions/Test123423235/Test123.java
> +}
wrong

2020-07-01 14:06 UTC, JulianSobott commented
Please change the title

2020-07-01 14:07 UTC, JulianSobott commented on submissions/Test123423235/CarRacingGame/Car.java
> +package CarRacingGame;
good

2020-07-01 15:50 UTC, JulianSobott requested changes
Very good solution. Some minor things are missing. But you can see that you understand java and you should be well prepared for the real exam. 
If you have any questions you can ask them below this comment or inside a review comment

2020-07-01 15:50 UTC, JulianSobott commented on submissions/Test123423235/CarRacingGame/IRenderObject.java
> +    public abstract void render();
`public abstract` is the default in an interface and is therefore not needed. But it is not wrong.

2020-07-01 15:50 UTC, JulianSobott commented on submissions/Test123423235/CarRacingGame/Car.java
> +
constructor with no arguments is missing. (in which all values are set to 0)

2020-07-01 15:50 UTC, JulianSobott commented on submissions/Test123423235/CarRacingGame/Motorbike.java
> +    public Motorbike (double x, double y, double rotation){
`double tiltAngle` is missing as parameter.

2020-07-01 15:50 UTC, JulianSobott commented on submissions/Test123423235/CarRacingGame/Motorbike.java
> +        super(0,0,0);
Better call: `this(0, 0, 0, 0)`. to also set the `tiltAngle`

2020-07-01 15:50 UTC, JulianSobott commented on submissions/Test123423235/CarRacingGame/Renderer.java
> +    private IRenderObject[] Store = new IRenderObject[0];
In Java, attributes should start with a lowercase. -> `store` otherwise it is easily confused with a class. This is not wrong just a convention.

2020-07-01 15:50 UTC, JulianSobott commented on submissions/Test123423235/CarRacingGame/Renderer.java
> +        for ( int i = 0; i < Store.length; i ++){
> If the `object` is already in the array (`equals`) do nothing and return `false`.

Possible solution: This check can be added to the for loop and move the actual assignment after the for loop. e.g. in the else case of the if

2020-07-01 15:50 UTC, JulianSobott commented on submissions/Test123423235/CarRacingGame/Renderer.java
> +                System.out.println(i);
`i.render();`  instead of the print. The output is the same, but later on `render()` could be implemented.

2020-07-01 20:27 UTC, JulianSobott reviewed
Except for the `addRenderObject()` function everything is good now.

2020-07-01 20:27 UTC, JulianSobott commented on submissions/Test123423235/CarRacingGame/Renderer.java
> -        for ( int i = 0; i < Store.length; i ++){
To add an object only if it is not already in the array you could use something like this:

```
public boolean addRenderObject(IRenderObject o) {
        int potentialSpace = -1;
        for(int i = 0; i < objects.length; i++) {
            if (objects[i] == null) {
                potentialSpace = i;
            }
            if(objects[i] != null && objects[i].equals(o)) {
                return false;
            }
        }
        if (potentialSpace != -1) {
            objects[potentialSpace] = o;
        } else {
// You can replace this part with your own expand function
            IRenderObject[] tmp = new IRenderObject[objects.length + 1]; 
            System.arraycopy(objects, 0, tmp, 0, objects.length);
            objects = tmp;
            objects[objects.length - 1] = o;
        }
        return true;
    }

```

2020-07-02 14:25 UTC, JulianSobott approved these changes
Everything should be correct now

2020-07-02 14:26 UTC, merged